apiVersion: v1
kind: ServiceAccount
metadata:
    name: svcs-acct-dply
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: account-role
    namespace: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: svcs-acct-dply
      namespace: default
    - kind: ServiceAccount
      name: svcs-acct-dply
      namespace: kube-system
