version: '3.4'
services:
    jenkins-docker:
        container_name: jenkins-docker
        network_mode: host
        build:
          context: .
          args:
            HOST_UID: 1001
            HOST_GID: 998
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - ./casc.yaml:/var/jenkins_home/casc.yaml
            - /var/run/docker.sock:/var/run/docker.sock
            - ../kubernetes/kubeconfig.json:/.kube/kubeconfig.json
        environment:
            JENKINS_ADMIN_ID: admin
            JENKINS_ADMIN_PASSWORD: admin
            K8S_AUTH_KUBECONFIG: /.kube/kubeconfig.json
